[base.'杀']
Diamonds = [6, 7, 8, 9, 13]
Clubs = [2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 10, 10, 11, 11]
Hearts = [10, 10, 11]
Spades = [7, 8, 8, 9, 9, 10, 10]
[base.'雷杀']
Clubs = [5, 6, 7, 8]
Spades = [4, 5, 6, 7, 8]
[base.'火杀']
Diamonds = [4, 5]
Hearts = [4, 7, 10]
[base.'闪']
Diamonds = [2, 2, 3, 4, 5, 6, 6, 7, 7, 8, 8, 9, 10, 10, 11, 11, 11]
Hearts = [2, 2, 8, 9, 11, 12, 13]
[base.'桃']
Diamonds = [2, 3, 12]
Hearts = [3, 4, 5, 6, 6, 7, 8, 9, 12]
[base.'酒']
Diamonds = [9]
Clubs = [3, 9]
Spades = [3, 9]

[spell.'桃园']
Hearts = [1]
[spell.'万箭']
Hearts = [1]
[spell.'借刀']
Clubs = [12, 13]
[spell.'五谷']
Hearts = [3, 4]
[spell.'南蛮']
Clubs = [7]
Spades = [7, 13]
[spell.'决斗']
Diamonds = [1]
Clubs = [1]
Spades = [1]
[spell.'火攻']
Diamonds = [12]
Hearts = [2, 3]
[spell.'无中']
Hearts = [7, 8, 9, 11]
[spell.'顺手']
Diamonds = [3, 4]
Spades = [3, 4, 11]
[spell.'过河']
Clubs = [3, 4]
Hearts = [12]
Spades = [3, 4, 12]
[spell.'铁索']
Clubs = [10, 11, 12, 13]
Spades = [11, 12]
[spell.'无懈']
Diamonds = [12]
Clubs = [12, 13]
Hearts = [1, 13]
Spades = [11, 13]

[delay.'闪电']
Hearts = [12]
Spades = [1]
[delay.'兵粮']
Clubs = [4]
Spades = [10]
[delay.'乐']
Clubs = [6]
Hearts = [6]
Spades = [6]

[wepaon.'连弩']
Diamonds = [1]
Clubs = [1]
[wepaon.'青釭']
Spades = [6]
[wepaon.'寒冰']
Spades = [2]
[wepaon.'雌雄']
Spades = [2]
[wepaon.'古锭']
Spades = [1]
[wepaon.'青龙']
Spades = [5]
[wepaon.'丈八']
Spades = [12]
[wepaon.'贯石']
Diamonds = [5]
[wepaon.'羽扇']
Diamonds = [1]
[wepaon.'画戟']
Diamonds = [12]
[wepaon.'麒麟']
Hearts = [5]

[armor.'狮子']
Clubs = [1]
[armor.'仁王']
Clubs = [1]
[armor.'藤甲']
Clubs = [2]
Spades = [2]
[armor.'八卦']
Clubs = [2]
Spades = [2]

[atkhorse.'攻马']
Diamonds = [13]
Hearts = [5]
Spades = [13]
[defhorse.'防马']
Diamonds = [13]
Clubs = [5]
Hearts = [13]
Spades = [5]
